name: expressions
description: A library to parse and evaluate simple dart and javascript like expressions.
version: 0.2.4
homepage: https://github.com/appsup-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  quiver: ^3.0.0
  petitparser: ^5.0.0
  rxdart: ^0.27.0
  fake_async: ^1.2.0
  meta: ^1.3.0


dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.11.0
